### ISSUE TITLE
Add extension support for .liquid

### ISSUE THREAD

**Issue by jaredmason** [EmranMR/AlpineJS-Nova-Extension#1]
Hi, would love support added for .liquid html files.

**Comment by EmranMR** [comment]
Hi @jaredmason !

Thank you for the request, can you elaborate more as I am not familiar with the .liquid files at all? would appreciate a link to their website as well 😊

Is it basically a template file mixing data with usual HTML? and you use the aplineJS outside the liquid syntax in the HTML context? A simple example would also help!

**Comment by jaredmason** [comment]
Yep you got it in one! AlpineJS has become quite popular in Shopify community amongst theme devs. Link to docs below.

https://shopify.dev/api/liquid

And this is the extension I'm using to add syntax highlighting/completion to Nova if that helps?

https://extensions.panic.com/extensions/me.arthr/me.arthr.Liquid/

**Comment by EmranMR** [comment]
Hi @jaredmason I just released an update, it should be working in liquid files now, however do let me know if there are any problems or if the extension is still not available in .liquid files as you would expect them! :)

**Comment by jaredmason** [comment]
Thanks @EmranMR it's working great. Appreciate it!
