### ISSUE TITLE
Add support for .twig extensions

### ISSUE THREAD

**Issue by imploding** [EmranMR/AlpineJS-Nova-Extension#2]
In a similar request to .liquid files, it would be great to access this extension in .twig files.

Twig shares a lot in common with liquid and vice-versa. [Here's the Nova extension I'm using for .twig](https://extensions.panic.com/extensions/tpmatthes/tpmatthes.Twig/)

It's great to see AlpineJS get more attention – thanks for your efforts!

**Comment by EmranMR** [comment]
Hi Matt! 👋

Thank you for the request and your kind words!

Please feel free to head over to the extension library and update the AlpineJS extension. It should all be working like a charm in any file with Twig syntax highlighting!

I am no expert in Twig template engine, however test drove the extension with your attached syntax highlighting extension and all seems to be working fine. 

Any **issues** or **bugs**? 🫣, please feel free to let me know and I will try to fix!
